Feat/#25/icon button
prgrms-web-devcourse/Team_WAS_YAS_FE pull request #37
Opened 2021-12-04 17:01 UTC by Junhyeong-B

## 🚅 PR 한 줄 요약

Atom Component - IconButton 컴포넌트 구현

## 🧑‍💻 PR 세부 내용

- IconButton
  - Play
  - RoutineUpdate
  - Add

-  `<IconButton.Play />` 버튼은 클릭했을 때 실행, 일시정지 형태로 변경됩니다
- `<IconButton.Play />`, `<IconButton.RoutineUpdate/>`, `<IconButton.Add/>` 형태로 사용 가능합니다.
- 미디어쿼리로 적용 되어있습니다 
- Closed #25 

## 📸 스크린샷

<img width="300"  src="https://user-images.githubusercontent.com/85148549/144717860-b4cccd71-9912-4dff-bb2a-dfa9e22fb9da.png">

2021-12-04 17:50 UTC, younoah requested changes
버튼마스터 준형님~~!! 고생하셨어요!! 👍👍👍👍

피드백 남겨드렸는데 참고 부탁드립니다~!!

2021-12-04 17:50 UTC, younoah commented on src/components/atoms/IconButton/Play.tsx
> +    <PlayBase onClick={userPlayHandler} {...props}>
아래와 같이 실제로 해당 컴포넌트를 사용할 때 외부에서 onClick 메서드를 주입하는 경우도 있을것 같은데요!
`<Button.Play onClick={handleClickPlayButton}>`

그렇다면 
`userPlayHandler` 함수내부에 porp으로 전달받은 onClick을 실행해주는게 좋지 않을까요!? 

```jsx
const userPlayHandler = (e): void => {
    setIsPlay((isPlay) => !isPlay);
    props.onClick && props.onClick(e);
  };
```
이렇게 작성한다면 함수명은 `handleClickPlayButton`과 같은 좀 더 명시적으로 네이밍하는게 좋을것 같네요!

2021-12-05 03:41 UTC, younoah commented
아! 그리고 `component/index.ts`에 모두 `export` 해주시면 좋을것 같습니다! 😀

2021-12-05 07:21 UTC, dasssseul reviewed
준형님 고생하셨습니다ㅎㅎ
리뷰 조금 남겨봤는데 그 부분들만 수정하고 머지하면 좋을 것 같아요~!!
조지 최고 ~~~👍

2021-12-05 07:21 UTC, dasssseul commented on src/components/atoms/RoundedButton/Base.tsx
> +}
RoundedButtonProps 부탁드립니다 🙇🏻‍♀️

2021-12-05 07:21 UTC, dasssseul commented on src/stories/components/atoms/RoundedButton.stories.tsx
> +export const Default = ({ ...args }): JSX.Element => {
요기서 {...args}:RoundedButtonProps 요렇게 명시해주면 좋을 것 같아요ㅎㅎ

2021-12-05 07:21 UTC, dasssseul commented on src/components/index.ts
> +export { RoundedButton } from './atoms/RoundedButton';
export type으로 props도 진행해주면 좋을 것 같습니다ㅎㅎ

2021-12-05 07:30 UTC, younoah requested changes
준형님!!! 피드백 하나 남겼는데 확인 부탁드립니다! 😃

2021-12-05 07:30 UTC, younoah commented on src/components/atoms/RoundedButton/Play.tsx
> +  };
일반적으로 `button` 컴포넌트를 사용할 때, 클릭했을 때의 핸들링 하는 메소드를 넘기는 프로퍼티의 이름은 `onClickc`을 기대할 것 같은데요!

```tsx
<RoundedButton.Play onClick={handleClickPlayButton}>
```
이런식으로요!!


현재대로라면 `onClick`과 `onPlayClick` 모두 prop으로 넘길수 있는데 `onClick`을 그대로 사용하는건 어떨까요!?  🤔

2021-12-05 07:33 UTC, Junhyeong-B commented on src/components/atoms/RoundedButton/Play.tsx
> +  };
오호..!!😃 그렇군요! 무의식중에 `onClick`이 아닌 다른 이름으로 주어야 한다는 생각이 있었네요..ㅎㅎ 이것도 반영할게요 리뷰 감사합니다~~

2021-12-05 07:37 UTC, merged